# ---------------------------------------------------------------------------
# MIL Platform — Development Makefile
#
# All targets run from the repository root.
# Run `make help` for a description of every target.
# ---------------------------------------------------------------------------

.DEFAULT_GOAL := help

# Python executable — prefer virtual environment if one is active.
PYTHON := python3
PIP    := pip3

# Source directories
SRC_DIR   := src
TEST_DIR  := tests

# Alembic configuration at repository root
ALEMBIC   := alembic --config alembic.ini

.PHONY: help install install-dev lint format type-check \
        test test-unit test-integration test-contract test-providers \
        migrate migrate-check migrate-history migrate-rollback \
        run-api run-worker run-scheduler \
        docker-up docker-down docker-reset \
        clean

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------

help: ## Show this help message
	@echo ""
	@echo "MIL Platform — Development Commands"
	@echo "===================================="
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'
	@echo ""

# ---------------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------------

install: ## Install the platform package in editable mode (core deps only)
	$(PIP) install -e .

install-dev: ## Install the platform package with all development dependencies
	$(PIP) install -e ".[dev]"

# ---------------------------------------------------------------------------
# Linting and formatting
# Targets are independent: lint checks, format auto-fixes.
# ---------------------------------------------------------------------------

lint: ## Run ruff linter across src/ and tests/
	ruff check $(SRC_DIR) $(TEST_DIR)

format: ## Auto-format code with ruff formatter
	ruff format $(SRC_DIR) $(TEST_DIR)

format-check: ## Verify formatting without making changes (for CI)
	ruff format --check $(SRC_DIR) $(TEST_DIR)

type-check: ## Run mypy type checker
	mypy $(SRC_DIR)

check: lint format-check type-check ## Run all static analysis checks (CI gate)

# ---------------------------------------------------------------------------
# Testing
# Each target maps to a pytest marker.
# Integration and contract tests require docker-up first.
# ---------------------------------------------------------------------------

test: ## Run the complete test suite (all markers)
	pytest $(TEST_DIR) -v --tb=short

test-unit: ## Run unit tests only (no infrastructure required)
	pytest $(TEST_DIR)/unit -v --tb=short -m unit

test-integration: ## Run integration tests (requires: make docker-up && make migrate)
	pytest $(TEST_DIR)/integration -v --tb=short -m integration

test-contract: ## Run API contract tests (requires: make run-api in another terminal)
	pytest $(TEST_DIR)/contract -v --tb=short -m contract

test-providers: ## Run provider conformance tests
	pytest $(TEST_DIR)/providers -v --tb=short -m providers

test-cov: ## Run unit tests with coverage report
	pytest $(TEST_DIR)/unit -v --tb=short -m unit \
		--cov=$(SRC_DIR) \
		--cov-report=term-missing \
		--cov-report=html:htmlcov

# ---------------------------------------------------------------------------
# Database migrations (Alembic)
# The database must be reachable. Configure POSTGRES_* or ALEMBIC_DATABASE_URL.
# Start the database first: make docker-up
# ---------------------------------------------------------------------------

migrate: ## Apply all pending migrations (alembic upgrade head)
	$(ALEMBIC) upgrade head

migrate-check: ## Show pending migrations without applying them
	$(ALEMBIC) upgrade head --sql

migrate-history: ## Show the full migration history
	$(ALEMBIC) history --verbose

migrate-rollback: ## Roll back the most recent migration
	$(ALEMBIC) downgrade -1

migrate-new: ## Generate a new autogenerated migration (usage: make migrate-new MSG="description")
	@if [ -z "$(MSG)" ]; then \
		echo "Error: provide a description with MSG=\"your description\""; \
		exit 1; \
	fi
	$(ALEMBIC) revision --autogenerate -m "$(MSG)"

# ---------------------------------------------------------------------------
# Application processes
# These targets start the application. Dependencies (docker-up, migrate)
# must be completed first. Implementations become available after Sprint 2.
# ---------------------------------------------------------------------------

run-api: ## Start the MIL API server (requires Sprint 2+ implementation)
	uvicorn mil.main:app \
		--host $${MIL_HOST:-0.0.0.0} \
		--port $${MIL_PORT:-8000} \
		--reload \
		--reload-dir $(SRC_DIR)

run-worker: ## Start the document pipeline and finding generation workers
	$(PYTHON) -m workers.document_pipeline &
	$(PYTHON) -m workers.finding_generation

run-scheduler: ## Start the operational intelligence scheduler (periodic snapshots)
	$(PYTHON) -m workers.operational_snapshots

# ---------------------------------------------------------------------------
# Docker infrastructure
# Manages the local development services defined in docker-compose.yml.
# ---------------------------------------------------------------------------

docker-up: ## Start local infrastructure (PostgreSQL, MinIO, Redis)
	docker compose up -d
	@echo "Waiting for services to be healthy..."
	@docker compose ps

docker-down: ## Stop local infrastructure (data preserved in volumes)
	docker compose down

docker-reset: ## Stop local infrastructure and delete all data volumes
	docker compose down -v
	@echo "All volumes removed. Run make docker-up && make migrate to reinitialise."

docker-logs: ## Stream logs from all infrastructure services
	docker compose logs -f

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

clean: ## Remove build artefacts, caches, and coverage reports
	find . -type d -name "__pycache__" -not -path "./.git/*" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name "*.egg-info"  -not -path "./.git/*" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".mypy_cache"   -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name ".ruff_cache"   -exec rm -rf {} + 2>/dev/null || true
	rm -rf htmlcov .coverage coverage.xml
	@echo "Clean complete."
